"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.infra = exports.imageTag = exports.location = exports.stack = exports.config = void 0;
const pulumi = require("@pulumi/pulumi");
const gcp = require("@pulumi/gcp");
exports.config = new pulumi.Config();
exports.stack = pulumi.getStack();
exports.location = gcp.config.region || 'us-central1';
exports.imageTag = exports.config.require('tag');
exports.infra = new pulumi.StackReference(`idoshamun/infra/${exports.stack}`);
